site_name: AutoTech's Docs

nav:
  - Home: index.md
  - Lidar.md
  - IA.md
  - Asservissement.md
  - How to create documentation: building_docs.md
  - Regle de la course: https://ajuton-ens.github.io/CourseVoituresAutonomesSaclay/

theme: 
  title: AutoTech's Docs
  name: readthedocs
  logo: img/autotech_logo.jpeg
  #locale: fr # does not work idk why -Arnaud

repo_url: https://github.com/Club-INTech/CoVAPSy/

site_description: "AutoTech est un projet du Club de robotique INTech de Telecom SudParis et IMT Business School. Il a pour but de concevoir un véhicule autonome pour la compétition CoVAPSy."

# site_author: "AutoTech"

# exclude_docs: |
#   api-config.json    # A file with this name anywhere.
#   /requirements.txt  # Top-level "docs/requirements.txt".
#   *.py               # Any file with this extension anywhere.
#   !/foo/example.py   # But keep this particular file.

markdown_extensions:
  - admonition # This is a plugin for adding colored boxes for notes, warnings, etc.